
"use client";

import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import Image from "next/image";
import { ArrowLeft } from "lucide-react";
import { useRouter } from "next/navigation";
import { initialProducts } from "@/lib/mockData"; // Assuming products have some data

// Simulate more comprehensive product profit data
const allProductsProfitData = initialProducts.map((product, index) => ({
  ...product,
  // Simplified profit calculation for demo: (price - (cost_percentage * price)) * units_sold
  // Assuming cost is 60% of price for simplicity
  profit: (product.price * 0.4 * (product.stock > 0 ? (5 + index * 3) : 0)) + (Math.random() * 500), 
  unitsSold: (product.stock > 0 ? (5 + index * 3) : 0) + Math.floor(Math.random() * 30), 
}));

export default function AllProductsProfitPage() {
  const router = useRouter();

  return (
    <div className="flex flex-col gap-6">
      <div className="flex items-center justify-between">
        <h1 className="text-3xl font-bold">All Products Profit</h1>
        <Button variant="outline" onClick={() => router.back()}>
          <ArrowLeft className="mr-2 h-4 w-4" /> Back to Profit Report
        </Button>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Product Profit Breakdown</CardTitle>
          <CardDescription>Profit generated by each product.</CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="hidden sm:table-cell">Image</TableHead>
                <TableHead>Product Name</TableHead>
                <TableHead>Category</TableHead>
                <TableHead className="text-right">Total Profit</TableHead>
                <TableHead className="text-right">Units Sold</TableHead>
                <TableHead className="text-right">Profit/Unit</TableHead>
                <TableHead className="text-center">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {allProductsProfitData.map((product) => (
                <TableRow key={product.id}>
                  <TableCell className="hidden sm:table-cell">
                    <Image
                      src={product.images[0] || "https://placehold.co/40x40.png"}
                      alt={product.name}
                      width={40}
                      height={40}
                      className="rounded-md object-cover"
                      data-ai-hint={product.dataAiHints[0] || "product image"}
                    />
                  </TableCell>
                  <TableCell>
                    <Link href={`/products/${product.id}`} className="font-medium hover:underline">
                      {product.name}
                    </Link>
                  </TableCell>
                  <TableCell>{product.category}</TableCell>
                  <TableCell className="text-right">ZMW {product.profit.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2})}</TableCell>
                  <TableCell className="text-right">{product.unitsSold}</TableCell>
                  <TableCell className="text-right">
                    {product.unitsSold > 0 ? `ZMW ${(product.profit / product.unitsSold).toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2})}` : "ZMW 0.00"}
                  </TableCell>
                  <TableCell className="text-center">
                    <Button variant="outline" size="sm" asChild>
                      <Link href={`/products/${product.id}`}>View Product</Link>
                    </Button>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
          {allProductsProfitData.length === 0 && (
            <p className="text-center text-muted-foreground py-4">No product profit data available.</p>
          )}
        </CardContent>
      </Card>
    </div>
  );
}

